### PR TITLE
Just testing, please do not merge

### PR DESCRIPTION
**Pull request by marcelotrevisani**

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
This is just for testing purposes. I modified this part on ``conda-smithy`` and I just wanted to see if it will work in a real feedstock
I also modified the ``azure`` configuration for ``osx`` and ``win`` to run ``conda-press``, but first I would like to see it working on Linux

**Comment by marcelotrevisani** [comment]
I found a bug on ``conda-press``, haha
I will fix it

**Comment by scopatz** [comment]
:+1:

**Comment by marcelotrevisani** [comment]
Well, it is working! haha
I just think that would be good to specify a folder and ``conda-press`` will discover and convert all the packages

**Pull request closed without merging**
